/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errorsUnregisteredRouteImport } from './routes/(errors)/unregistered'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthPopupCallbackRouteImport } from './routes/auth/popup-callback'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as DevotionIndexRouteImport } from './routes/devotion/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAttendanceIndexRouteImport } from './routes/_authenticated/attendance/index'
import { Route as AuthenticatedBibleApiTesterIndexRouteImport } from './routes/_authenticated/bible-api-tester/index'
import { Route as AuthenticatedBibleIndexRouteImport } from './routes/_authenticated/bible/index'
import { Route as AuthenticatedChangePasswordIndexRouteImport } from './routes/_authenticated/change-password/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedDevotionRemindersIndexRouteImport } from './routes/_authenticated/devotion-reminders/index'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedGroupCareIndexRouteImport } from './routes/_authenticated/group-care/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedLambInfoIndexRouteImport } from './routes/_authenticated/lamb-info/index'
import { Route as AuthenticatedNewsNewRouteImport } from './routes/_authenticated/news/new'
import { Route as AuthenticatedNewsTableRouteImport } from './routes/_authenticated/news/table'
import { Route as AuthenticatedPermissionsIndexRouteImport } from './routes/_authenticated/permissions/index'
import { Route as AuthenticatedPersonalityTypeIndexRouteImport } from './routes/_authenticated/personality-type/index'
import { Route as AuthenticatedPrayerListIndexRouteImport } from './routes/_authenticated/prayer-list/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSpiritualGiftsSurveyIndexRouteImport } from './routes/_authenticated/spiritual-gifts-survey/index'
import { Route as AuthenticatedSubscribeIndexRouteImport } from './routes/_authenticated/subscribe/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedUserRolesIndexRouteImport } from './routes/_authenticated/user-roles/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as DevotionDevotionIdIndexRouteImport } from './routes/devotion/$devotionId/index'
import { Route as NewsSlugIndexRouteImport } from './routes/news/$slug/index'
import { Route as AuthenticatedBibleBookChapterRouteImport } from './routes/_authenticated/bible/$book/$chapter'
import { Route as AuthenticatedLambInfoLambIdIndexRouteImport } from './routes/_authenticated/lamb-info/$lambId/index'
import { Route as AuthenticatedLambInfoLambIdDevotionRouteImport } from './routes/_authenticated/lamb-info/$lambId/devotion'
import { Route as AuthenticatedLambInfoDevotionIndexRouteImport } from './routes/_authenticated/lamb-info/devotion/index'
import { Route as AuthenticatedLambInfoDevotionNewRouteImport } from './routes/_authenticated/lamb-info/devotion/new'
import { Route as AuthenticatedLambInfoDevotionTableRouteImport } from './routes/_authenticated/lamb-info/devotion/table'
import { Route as AuthenticatedNewsNewsIdEditRouteImport } from './routes/_authenticated/news/$newsId/edit'
import { Route as AuthenticatedBibleLiveBookChapterIndexRouteImport } from './routes/_authenticated/bible-live/$book/$chapter/index'
import { Route as AuthenticatedLambInfoDevotionDevotionIdIndexRouteImport } from './routes/_authenticated/lamb-info/devotion/$devotionId/index'
import { Route as AuthenticatedLambInfoDevotionDevotionIdEditRouteImport } from './routes/_authenticated/lamb-info/devotion/$devotionId/edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errorsUnregisteredRoute = errorsUnregisteredRouteImport.update({
  id: '/(errors)/unregistered',
  path: '/unregistered',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthPopupCallbackRoute = AuthPopupCallbackRouteImport.update({
  id: '/auth/popup-callback',
  path: '/auth/popup-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const DevotionIndexRoute = DevotionIndexRouteImport.update({
  id: '/devotion/',
  path: '/devotion/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceIndexRoute =
  AuthenticatedAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibleApiTesterIndexRoute =
  AuthenticatedBibleApiTesterIndexRouteImport.update({
    id: '/bible-api-tester/',
    path: '/bible-api-tester/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibleIndexRoute = AuthenticatedBibleIndexRouteImport.update({
  id: '/bible/',
  path: '/bible/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordIndexRoute =
  AuthenticatedChangePasswordIndexRouteImport.update({
    id: '/change-password/',
    path: '/change-password/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevotionRemindersIndexRoute =
  AuthenticatedDevotionRemindersIndexRouteImport.update({
    id: '/devotion-reminders/',
    path: '/devotion-reminders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupCareIndexRoute =
  AuthenticatedGroupCareIndexRouteImport.update({
    id: '/group-care/',
    path: '/group-care/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLambInfoIndexRoute =
  AuthenticatedLambInfoIndexRouteImport.update({
    id: '/lamb-info/',
    path: '/lamb-info/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewsNewRoute = AuthenticatedNewsNewRouteImport.update({
  id: '/news/new',
  path: '/news/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsTableRoute = AuthenticatedNewsTableRouteImport.update({
  id: '/news/table',
  path: '/news/table',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissionsIndexRoute =
  AuthenticatedPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPersonalityTypeIndexRoute =
  AuthenticatedPersonalityTypeIndexRouteImport.update({
    id: '/personality-type/',
    path: '/personality-type/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrayerListIndexRoute =
  AuthenticatedPrayerListIndexRouteImport.update({
    id: '/prayer-list/',
    path: '/prayer-list/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSpiritualGiftsSurveyIndexRoute =
  AuthenticatedSpiritualGiftsSurveyIndexRouteImport.update({
    id: '/spiritual-gifts-survey/',
    path: '/spiritual-gifts-survey/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubscribeIndexRoute =
  AuthenticatedSubscribeIndexRouteImport.update({
    id: '/subscribe/',
    path: '/subscribe/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserRolesIndexRoute =
  AuthenticatedUserRolesIndexRouteImport.update({
    id: '/user-roles/',
    path: '/user-roles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const DevotionDevotionIdIndexRoute = DevotionDevotionIdIndexRouteImport.update({
  id: '/devotion/$devotionId/',
  path: '/devotion/$devotionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugIndexRoute = NewsSlugIndexRouteImport.update({
  id: '/news/$slug/',
  path: '/news/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBibleBookChapterRoute =
  AuthenticatedBibleBookChapterRouteImport.update({
    id: '/bible/$book/$chapter',
    path: '/bible/$book/$chapter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLambInfoLambIdIndexRoute =
  AuthenticatedLambInfoLambIdIndexRouteImport.update({
    id: '/lamb-info/$lambId/',
    path: '/lamb-info/$lambId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLambInfoLambIdDevotionRoute =
  AuthenticatedLambInfoLambIdDevotionRouteImport.update({
    id: '/lamb-info/$lambId/devotion',
    path: '/lamb-info/$lambId/devotion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLambInfoDevotionIndexRoute =
  AuthenticatedLambInfoDevotionIndexRouteImport.update({
    id: '/lamb-info/devotion/',
    path: '/lamb-info/devotion/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLambInfoDevotionNewRoute =
  AuthenticatedLambInfoDevotionNewRouteImport.update({
    id: '/lamb-info/devotion/new',
    path: '/lamb-info/devotion/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLambInfoDevotionTableRoute =
  AuthenticatedLambInfoDevotionTableRouteImport.update({
    id: '/lamb-info/devotion/table',
    path: '/lamb-info/devotion/table',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewsNewsIdEditRoute =
  AuthenticatedNewsNewsIdEditRouteImport.update({
    id: '/news/$newsId/edit',
    path: '/news/$newsId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibleLiveBookChapterIndexRoute =
  AuthenticatedBibleLiveBookChapterIndexRouteImport.update({
    id: '/bible-live/$book/$chapter/',
    path: '/bible-live/$book/$chapter/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLambInfoDevotionDevotionIdIndexRoute =
  AuthenticatedLambInfoDevotionDevotionIdIndexRouteImport.update({
    id: '/lamb-info/devotion/$devotionId/',
    path: '/lamb-info/devotion/$devotionId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLambInfoDevotionDevotionIdEditRoute =
  AuthenticatedLambInfoDevotionDevotionIdEditRouteImport.update({
    id: '/lamb-info/devotion/$devotionId/edit',
    path: '/lamb-info/devotion/$devotionId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkauthRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/unregistered': typeof errorsUnregisteredRoute
  '/auth/popup-callback': typeof AuthPopupCallbackRoute
  '/devotion/': typeof DevotionIndexRoute
  '/news/': typeof NewsIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/news/new': typeof AuthenticatedNewsNewRoute
  '/news/table': typeof AuthenticatedNewsTableRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/bible-api-tester/': typeof AuthenticatedBibleApiTesterIndexRoute
  '/bible/': typeof AuthenticatedBibleIndexRoute
  '/change-password/': typeof AuthenticatedChangePasswordIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/devotion-reminders/': typeof AuthenticatedDevotionRemindersIndexRoute
  '/group-care/': typeof AuthenticatedGroupCareIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/lamb-info/': typeof AuthenticatedLambInfoIndexRoute
  '/permissions/': typeof AuthenticatedPermissionsIndexRoute
  '/personality-type/': typeof AuthenticatedPersonalityTypeIndexRoute
  '/prayer-list/': typeof AuthenticatedPrayerListIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/spiritual-gifts-survey/': typeof AuthenticatedSpiritualGiftsSurveyIndexRoute
  '/subscribe/': typeof AuthenticatedSubscribeIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/user-roles/': typeof AuthenticatedUserRolesIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/devotion/$devotionId/': typeof DevotionDevotionIdIndexRoute
  '/news/$slug/': typeof NewsSlugIndexRoute
  '/bible/$book/$chapter': typeof AuthenticatedBibleBookChapterRoute
  '/lamb-info/$lambId/devotion': typeof AuthenticatedLambInfoLambIdDevotionRoute
  '/lamb-info/devotion/new': typeof AuthenticatedLambInfoDevotionNewRoute
  '/lamb-info/devotion/table': typeof AuthenticatedLambInfoDevotionTableRoute
  '/news/$newsId/edit': typeof AuthenticatedNewsNewsIdEditRoute
  '/lamb-info/$lambId/': typeof AuthenticatedLambInfoLambIdIndexRoute
  '/lamb-info/devotion/': typeof AuthenticatedLambInfoDevotionIndexRoute
  '/lamb-info/devotion/$devotionId/edit': typeof AuthenticatedLambInfoDevotionDevotionIdEditRoute
  '/bible-live/$book/$chapter/': typeof AuthenticatedBibleLiveBookChapterIndexRoute
  '/lamb-info/devotion/$devotionId/': typeof AuthenticatedLambInfoDevotionDevotionIdIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkauthRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/unregistered': typeof errorsUnregisteredRoute
  '/auth/popup-callback': typeof AuthPopupCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/devotion': typeof DevotionIndexRoute
  '/news': typeof NewsIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/news/new': typeof AuthenticatedNewsNewRoute
  '/news/table': typeof AuthenticatedNewsTableRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
  '/bible-api-tester': typeof AuthenticatedBibleApiTesterIndexRoute
  '/bible': typeof AuthenticatedBibleIndexRoute
  '/change-password': typeof AuthenticatedChangePasswordIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/devotion-reminders': typeof AuthenticatedDevotionRemindersIndexRoute
  '/group-care': typeof AuthenticatedGroupCareIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/lamb-info': typeof AuthenticatedLambInfoIndexRoute
  '/permissions': typeof AuthenticatedPermissionsIndexRoute
  '/personality-type': typeof AuthenticatedPersonalityTypeIndexRoute
  '/prayer-list': typeof AuthenticatedPrayerListIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/spiritual-gifts-survey': typeof AuthenticatedSpiritualGiftsSurveyIndexRoute
  '/subscribe': typeof AuthenticatedSubscribeIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/user-roles': typeof AuthenticatedUserRolesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/devotion/$devotionId': typeof DevotionDevotionIdIndexRoute
  '/news/$slug': typeof NewsSlugIndexRoute
  '/bible/$book/$chapter': typeof AuthenticatedBibleBookChapterRoute
  '/lamb-info/$lambId/devotion': typeof AuthenticatedLambInfoLambIdDevotionRoute
  '/lamb-info/devotion/new': typeof AuthenticatedLambInfoDevotionNewRoute
  '/lamb-info/devotion/table': typeof AuthenticatedLambInfoDevotionTableRoute
  '/news/$newsId/edit': typeof AuthenticatedNewsNewsIdEditRoute
  '/lamb-info/$lambId': typeof AuthenticatedLambInfoLambIdIndexRoute
  '/lamb-info/devotion': typeof AuthenticatedLambInfoDevotionIndexRoute
  '/lamb-info/devotion/$devotionId/edit': typeof AuthenticatedLambInfoDevotionDevotionIdEditRoute
  '/bible-live/$book/$chapter': typeof AuthenticatedBibleLiveBookChapterIndexRoute
  '/lamb-info/devotion/$devotionId': typeof AuthenticatedLambInfoDevotionDevotionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/(errors)/unregistered': typeof errorsUnregisteredRoute
  '/auth/popup-callback': typeof AuthPopupCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/devotion/': typeof DevotionIndexRoute
  '/news/': typeof NewsIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/news/new': typeof AuthenticatedNewsNewRoute
  '/_authenticated/news/table': typeof AuthenticatedNewsTableRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/_authenticated/bible-api-tester/': typeof AuthenticatedBibleApiTesterIndexRoute
  '/_authenticated/bible/': typeof AuthenticatedBibleIndexRoute
  '/_authenticated/change-password/': typeof AuthenticatedChangePasswordIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/devotion-reminders/': typeof AuthenticatedDevotionRemindersIndexRoute
  '/_authenticated/group-care/': typeof AuthenticatedGroupCareIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/lamb-info/': typeof AuthenticatedLambInfoIndexRoute
  '/_authenticated/permissions/': typeof AuthenticatedPermissionsIndexRoute
  '/_authenticated/personality-type/': typeof AuthenticatedPersonalityTypeIndexRoute
  '/_authenticated/prayer-list/': typeof AuthenticatedPrayerListIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/spiritual-gifts-survey/': typeof AuthenticatedSpiritualGiftsSurveyIndexRoute
  '/_authenticated/subscribe/': typeof AuthenticatedSubscribeIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/user-roles/': typeof AuthenticatedUserRolesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/devotion/$devotionId/': typeof DevotionDevotionIdIndexRoute
  '/news/$slug/': typeof NewsSlugIndexRoute
  '/_authenticated/bible/$book/$chapter': typeof AuthenticatedBibleBookChapterRoute
  '/_authenticated/lamb-info/$lambId/devotion': typeof AuthenticatedLambInfoLambIdDevotionRoute
  '/_authenticated/lamb-info/devotion/new': typeof AuthenticatedLambInfoDevotionNewRoute
  '/_authenticated/lamb-info/devotion/table': typeof AuthenticatedLambInfoDevotionTableRoute
  '/_authenticated/news/$newsId/edit': typeof AuthenticatedNewsNewsIdEditRoute
  '/_authenticated/lamb-info/$lambId/': typeof AuthenticatedLambInfoLambIdIndexRoute
  '/_authenticated/lamb-info/devotion/': typeof AuthenticatedLambInfoDevotionIndexRoute
  '/_authenticated/lamb-info/devotion/$devotionId/edit': typeof AuthenticatedLambInfoDevotionDevotionIdEditRoute
  '/_authenticated/bible-live/$book/$chapter/': typeof AuthenticatedBibleLiveBookChapterIndexRoute
  '/_authenticated/lamb-info/devotion/$devotionId/': typeof AuthenticatedLambInfoDevotionDevotionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/unregistered'
    | '/auth/popup-callback'
    | '/devotion/'
    | '/news/'
    | '/errors/$error'
    | '/news/new'
    | '/news/table'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps/'
    | '/attendance/'
    | '/bible-api-tester/'
    | '/bible/'
    | '/change-password/'
    | '/chats/'
    | '/devotion-reminders/'
    | '/group-care/'
    | '/help-center/'
    | '/lamb-info/'
    | '/permissions/'
    | '/personality-type/'
    | '/prayer-list/'
    | '/settings/'
    | '/spiritual-gifts-survey/'
    | '/subscribe/'
    | '/tasks/'
    | '/user-roles/'
    | '/users/'
    | '/devotion/$devotionId/'
    | '/news/$slug/'
    | '/bible/$book/$chapter'
    | '/lamb-info/$lambId/devotion'
    | '/lamb-info/devotion/new'
    | '/lamb-info/devotion/table'
    | '/news/$newsId/edit'
    | '/lamb-info/$lambId/'
    | '/lamb-info/devotion/'
    | '/lamb-info/devotion/$devotionId/edit'
    | '/bible-live/$book/$chapter/'
    | '/lamb-info/devotion/$devotionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/unregistered'
    | '/auth/popup-callback'
    | '/'
    | '/devotion'
    | '/news'
    | '/errors/$error'
    | '/news/new'
    | '/news/table'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/attendance'
    | '/bible-api-tester'
    | '/bible'
    | '/change-password'
    | '/chats'
    | '/devotion-reminders'
    | '/group-care'
    | '/help-center'
    | '/lamb-info'
    | '/permissions'
    | '/personality-type'
    | '/prayer-list'
    | '/settings'
    | '/spiritual-gifts-survey'
    | '/subscribe'
    | '/tasks'
    | '/user-roles'
    | '/users'
    | '/devotion/$devotionId'
    | '/news/$slug'
    | '/bible/$book/$chapter'
    | '/lamb-info/$lambId/devotion'
    | '/lamb-info/devotion/new'
    | '/lamb-info/devotion/table'
    | '/news/$newsId/edit'
    | '/lamb-info/$lambId'
    | '/lamb-info/devotion'
    | '/lamb-info/devotion/$devotionId/edit'
    | '/bible-live/$book/$chapter'
    | '/lamb-info/devotion/$devotionId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/(errors)/unregistered'
    | '/auth/popup-callback'
    | '/_authenticated/'
    | '/devotion/'
    | '/news/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/news/new'
    | '/_authenticated/news/table'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/attendance/'
    | '/_authenticated/bible-api-tester/'
    | '/_authenticated/bible/'
    | '/_authenticated/change-password/'
    | '/_authenticated/chats/'
    | '/_authenticated/devotion-reminders/'
    | '/_authenticated/group-care/'
    | '/_authenticated/help-center/'
    | '/_authenticated/lamb-info/'
    | '/_authenticated/permissions/'
    | '/_authenticated/personality-type/'
    | '/_authenticated/prayer-list/'
    | '/_authenticated/settings/'
    | '/_authenticated/spiritual-gifts-survey/'
    | '/_authenticated/subscribe/'
    | '/_authenticated/tasks/'
    | '/_authenticated/user-roles/'
    | '/_authenticated/users/'
    | '/devotion/$devotionId/'
    | '/news/$slug/'
    | '/_authenticated/bible/$book/$chapter'
    | '/_authenticated/lamb-info/$lambId/devotion'
    | '/_authenticated/lamb-info/devotion/new'
    | '/_authenticated/lamb-info/devotion/table'
    | '/_authenticated/news/$newsId/edit'
    | '/_authenticated/lamb-info/$lambId/'
    | '/_authenticated/lamb-info/devotion/'
    | '/_authenticated/lamb-info/devotion/$devotionId/edit'
    | '/_authenticated/bible-live/$book/$chapter/'
    | '/_authenticated/lamb-info/devotion/$devotionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  errorsUnregisteredRoute: typeof errorsUnregisteredRoute
  AuthPopupCallbackRoute: typeof AuthPopupCallbackRoute
  DevotionIndexRoute: typeof DevotionIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  DevotionDevotionIdIndexRoute: typeof DevotionDevotionIdIndexRoute
  NewsSlugIndexRoute: typeof NewsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/unregistered': {
      id: '/(errors)/unregistered'
      path: '/unregistered'
      fullPath: '/unregistered'
      preLoaderRoute: typeof errorsUnregisteredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/popup-callback': {
      id: '/auth/popup-callback'
      path: '/auth/popup-callback'
      fullPath: '/auth/popup-callback'
      preLoaderRoute: typeof AuthPopupCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/devotion/': {
      id: '/devotion/'
      path: '/devotion'
      fullPath: '/devotion/'
      preLoaderRoute: typeof DevotionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/': {
      id: '/_authenticated/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AuthenticatedAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bible-api-tester/': {
      id: '/_authenticated/bible-api-tester/'
      path: '/bible-api-tester'
      fullPath: '/bible-api-tester/'
      preLoaderRoute: typeof AuthenticatedBibleApiTesterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bible/': {
      id: '/_authenticated/bible/'
      path: '/bible'
      fullPath: '/bible/'
      preLoaderRoute: typeof AuthenticatedBibleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password/': {
      id: '/_authenticated/change-password/'
      path: '/change-password'
      fullPath: '/change-password/'
      preLoaderRoute: typeof AuthenticatedChangePasswordIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devotion-reminders/': {
      id: '/_authenticated/devotion-reminders/'
      path: '/devotion-reminders'
      fullPath: '/devotion-reminders/'
      preLoaderRoute: typeof AuthenticatedDevotionRemindersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/group-care/': {
      id: '/_authenticated/group-care/'
      path: '/group-care'
      fullPath: '/group-care/'
      preLoaderRoute: typeof AuthenticatedGroupCareIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lamb-info/': {
      id: '/_authenticated/lamb-info/'
      path: '/lamb-info'
      fullPath: '/lamb-info/'
      preLoaderRoute: typeof AuthenticatedLambInfoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news/new': {
      id: '/_authenticated/news/new'
      path: '/news/new'
      fullPath: '/news/new'
      preLoaderRoute: typeof AuthenticatedNewsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news/table': {
      id: '/_authenticated/news/table'
      path: '/news/table'
      fullPath: '/news/table'
      preLoaderRoute: typeof AuthenticatedNewsTableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions/': {
      id: '/_authenticated/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof AuthenticatedPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personality-type/': {
      id: '/_authenticated/personality-type/'
      path: '/personality-type'
      fullPath: '/personality-type/'
      preLoaderRoute: typeof AuthenticatedPersonalityTypeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prayer-list/': {
      id: '/_authenticated/prayer-list/'
      path: '/prayer-list'
      fullPath: '/prayer-list/'
      preLoaderRoute: typeof AuthenticatedPrayerListIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/spiritual-gifts-survey/': {
      id: '/_authenticated/spiritual-gifts-survey/'
      path: '/spiritual-gifts-survey'
      fullPath: '/spiritual-gifts-survey/'
      preLoaderRoute: typeof AuthenticatedSpiritualGiftsSurveyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscribe/': {
      id: '/_authenticated/subscribe/'
      path: '/subscribe'
      fullPath: '/subscribe/'
      preLoaderRoute: typeof AuthenticatedSubscribeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user-roles/': {
      id: '/_authenticated/user-roles/'
      path: '/user-roles'
      fullPath: '/user-roles/'
      preLoaderRoute: typeof AuthenticatedUserRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/devotion/$devotionId/': {
      id: '/devotion/$devotionId/'
      path: '/devotion/$devotionId'
      fullPath: '/devotion/$devotionId/'
      preLoaderRoute: typeof DevotionDevotionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug/': {
      id: '/news/$slug/'
      path: '/news/$slug'
      fullPath: '/news/$slug/'
      preLoaderRoute: typeof NewsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bible/$book/$chapter': {
      id: '/_authenticated/bible/$book/$chapter'
      path: '/bible/$book/$chapter'
      fullPath: '/bible/$book/$chapter'
      preLoaderRoute: typeof AuthenticatedBibleBookChapterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lamb-info/$lambId/': {
      id: '/_authenticated/lamb-info/$lambId/'
      path: '/lamb-info/$lambId'
      fullPath: '/lamb-info/$lambId/'
      preLoaderRoute: typeof AuthenticatedLambInfoLambIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lamb-info/$lambId/devotion': {
      id: '/_authenticated/lamb-info/$lambId/devotion'
      path: '/lamb-info/$lambId/devotion'
      fullPath: '/lamb-info/$lambId/devotion'
      preLoaderRoute: typeof AuthenticatedLambInfoLambIdDevotionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lamb-info/devotion/': {
      id: '/_authenticated/lamb-info/devotion/'
      path: '/lamb-info/devotion'
      fullPath: '/lamb-info/devotion/'
      preLoaderRoute: typeof AuthenticatedLambInfoDevotionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lamb-info/devotion/new': {
      id: '/_authenticated/lamb-info/devotion/new'
      path: '/lamb-info/devotion/new'
      fullPath: '/lamb-info/devotion/new'
      preLoaderRoute: typeof AuthenticatedLambInfoDevotionNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lamb-info/devotion/table': {
      id: '/_authenticated/lamb-info/devotion/table'
      path: '/lamb-info/devotion/table'
      fullPath: '/lamb-info/devotion/table'
      preLoaderRoute: typeof AuthenticatedLambInfoDevotionTableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news/$newsId/edit': {
      id: '/_authenticated/news/$newsId/edit'
      path: '/news/$newsId/edit'
      fullPath: '/news/$newsId/edit'
      preLoaderRoute: typeof AuthenticatedNewsNewsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bible-live/$book/$chapter/': {
      id: '/_authenticated/bible-live/$book/$chapter/'
      path: '/bible-live/$book/$chapter'
      fullPath: '/bible-live/$book/$chapter/'
      preLoaderRoute: typeof AuthenticatedBibleLiveBookChapterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lamb-info/devotion/$devotionId/': {
      id: '/_authenticated/lamb-info/devotion/$devotionId/'
      path: '/lamb-info/devotion/$devotionId'
      fullPath: '/lamb-info/devotion/$devotionId/'
      preLoaderRoute: typeof AuthenticatedLambInfoDevotionDevotionIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lamb-info/devotion/$devotionId/edit': {
      id: '/_authenticated/lamb-info/devotion/$devotionId/edit'
      path: '/lamb-info/devotion/$devotionId/edit'
      fullPath: '/lamb-info/devotion/$devotionId/edit'
      preLoaderRoute: typeof AuthenticatedLambInfoDevotionDevotionIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedNewsNewRoute: typeof AuthenticatedNewsNewRoute
  AuthenticatedNewsTableRoute: typeof AuthenticatedNewsTableRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedAttendanceIndexRoute: typeof AuthenticatedAttendanceIndexRoute
  AuthenticatedBibleApiTesterIndexRoute: typeof AuthenticatedBibleApiTesterIndexRoute
  AuthenticatedBibleIndexRoute: typeof AuthenticatedBibleIndexRoute
  AuthenticatedChangePasswordIndexRoute: typeof AuthenticatedChangePasswordIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedDevotionRemindersIndexRoute: typeof AuthenticatedDevotionRemindersIndexRoute
  AuthenticatedGroupCareIndexRoute: typeof AuthenticatedGroupCareIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedLambInfoIndexRoute: typeof AuthenticatedLambInfoIndexRoute
  AuthenticatedPermissionsIndexRoute: typeof AuthenticatedPermissionsIndexRoute
  AuthenticatedPersonalityTypeIndexRoute: typeof AuthenticatedPersonalityTypeIndexRoute
  AuthenticatedPrayerListIndexRoute: typeof AuthenticatedPrayerListIndexRoute
  AuthenticatedSpiritualGiftsSurveyIndexRoute: typeof AuthenticatedSpiritualGiftsSurveyIndexRoute
  AuthenticatedSubscribeIndexRoute: typeof AuthenticatedSubscribeIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUserRolesIndexRoute: typeof AuthenticatedUserRolesIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedBibleBookChapterRoute: typeof AuthenticatedBibleBookChapterRoute
  AuthenticatedLambInfoLambIdDevotionRoute: typeof AuthenticatedLambInfoLambIdDevotionRoute
  AuthenticatedLambInfoDevotionNewRoute: typeof AuthenticatedLambInfoDevotionNewRoute
  AuthenticatedLambInfoDevotionTableRoute: typeof AuthenticatedLambInfoDevotionTableRoute
  AuthenticatedNewsNewsIdEditRoute: typeof AuthenticatedNewsNewsIdEditRoute
  AuthenticatedLambInfoLambIdIndexRoute: typeof AuthenticatedLambInfoLambIdIndexRoute
  AuthenticatedLambInfoDevotionIndexRoute: typeof AuthenticatedLambInfoDevotionIndexRoute
  AuthenticatedLambInfoDevotionDevotionIdEditRoute: typeof AuthenticatedLambInfoDevotionDevotionIdEditRoute
  AuthenticatedBibleLiveBookChapterIndexRoute: typeof AuthenticatedBibleLiveBookChapterIndexRoute
  AuthenticatedLambInfoDevotionDevotionIdIndexRoute: typeof AuthenticatedLambInfoDevotionDevotionIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedNewsNewRoute: AuthenticatedNewsNewRoute,
  AuthenticatedNewsTableRoute: AuthenticatedNewsTableRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedAttendanceIndexRoute: AuthenticatedAttendanceIndexRoute,
  AuthenticatedBibleApiTesterIndexRoute: AuthenticatedBibleApiTesterIndexRoute,
  AuthenticatedBibleIndexRoute: AuthenticatedBibleIndexRoute,
  AuthenticatedChangePasswordIndexRoute: AuthenticatedChangePasswordIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedDevotionRemindersIndexRoute:
    AuthenticatedDevotionRemindersIndexRoute,
  AuthenticatedGroupCareIndexRoute: AuthenticatedGroupCareIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedLambInfoIndexRoute: AuthenticatedLambInfoIndexRoute,
  AuthenticatedPermissionsIndexRoute: AuthenticatedPermissionsIndexRoute,
  AuthenticatedPersonalityTypeIndexRoute:
    AuthenticatedPersonalityTypeIndexRoute,
  AuthenticatedPrayerListIndexRoute: AuthenticatedPrayerListIndexRoute,
  AuthenticatedSpiritualGiftsSurveyIndexRoute:
    AuthenticatedSpiritualGiftsSurveyIndexRoute,
  AuthenticatedSubscribeIndexRoute: AuthenticatedSubscribeIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUserRolesIndexRoute: AuthenticatedUserRolesIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedBibleBookChapterRoute: AuthenticatedBibleBookChapterRoute,
  AuthenticatedLambInfoLambIdDevotionRoute:
    AuthenticatedLambInfoLambIdDevotionRoute,
  AuthenticatedLambInfoDevotionNewRoute: AuthenticatedLambInfoDevotionNewRoute,
  AuthenticatedLambInfoDevotionTableRoute:
    AuthenticatedLambInfoDevotionTableRoute,
  AuthenticatedNewsNewsIdEditRoute: AuthenticatedNewsNewsIdEditRoute,
  AuthenticatedLambInfoLambIdIndexRoute: AuthenticatedLambInfoLambIdIndexRoute,
  AuthenticatedLambInfoDevotionIndexRoute:
    AuthenticatedLambInfoDevotionIndexRoute,
  AuthenticatedLambInfoDevotionDevotionIdEditRoute:
    AuthenticatedLambInfoDevotionDevotionIdEditRoute,
  AuthenticatedBibleLiveBookChapterIndexRoute:
    AuthenticatedBibleLiveBookChapterIndexRoute,
  AuthenticatedLambInfoDevotionDevotionIdIndexRoute:
    AuthenticatedLambInfoDevotionDevotionIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  errorsUnregisteredRoute: errorsUnregisteredRoute,
  AuthPopupCallbackRoute: AuthPopupCallbackRoute,
  DevotionIndexRoute: DevotionIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  DevotionDevotionIdIndexRoute: DevotionDevotionIdIndexRoute,
  NewsSlugIndexRoute: NewsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
